repos:
  # Lint and format Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi ]
  # Type check Python code
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      -  id: mypy
         args: [
           "--python-version=3.12",
           "--strict",
           "--ignore-missing-imports"
         ]
         exclude: tests/

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Basic file checks
      - id: check-yaml
        name: check yaml files
      - id: check-toml
        name: check toml files
      - id: check-json
        name: check json files
      - id: pretty-format-json
        name: pretty format json files
        types: [json]
      
      # Python-specific checks
      - id: debug-statements
        name: check for debug statements
      - id: name-tests-test
        name: check test naming
        args: [--pytest-test-first]

      # Security checks
      # This should never be needed but it's also good to have
      - id: detect-aws-credentials
        name: detect AWS credentials
      - id: detect-private-key
        name: detect private keys

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly