name: Commit Unit Tests

on: [push]

jobs:
  test-package:
    uses: ./.github/workflows/run_unit_tests.yml

  coverage-report:
    uses: ./.github/workflows/report_coverage.yml
    needs: [ test-package ]

  update-docs:
    uses: ./.github/workflows/update_docs.yml
    needs: [ test-package ]