name: Tests

on: [push, pull_request]

jobs:
  test-package:
    uses: ./.github/workflows/run_unit_tests.yml

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for accurate git revision dates
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: Install dependencies
        run: uv sync --all-extras --frozen

      - name: Build documentation with strict mode
        run: uv run --frozen mkdocs build --strict

  update-docs:
    # Only deploy docs on pushes to main (not on PRs)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/update_docs.yml
    needs: [ test-package, check-docs ]