name: Report Coverage

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: Install dependencies
        run: uv sync --all-extras --frozen

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: astra-coverage-report
          path: .coverage

      - name: Generate coverage report
        run: uv run --frozen coverage report

      - name: Coveralls
        uses: coverallsapp/github-action@v2