# This workflow will run only if the only changes made are in the docs folder.
# This enables quick fixes to documentation to be deployed without running the entire test suite.

name: Update Docs

on: [ workflow_call ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: Install dependencies
        run: uv sync --all-extras --frozen

      - name: Build documentation
        run: uv run --frozen mkdocs build

      - name: Deploy documentation
        run: uv run --frozen mkdocs gh-deploy --force